# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./my-app/package-lock.json
    - name: Check if my-app directory exists
      run: |
        if [ ! -d "my-app" ]; then
          echo "my-app directory does not exist"
          exit 1
        fi
    - name: Install dependencies
      run: npm ci
      working-directory: ./my-app
    - name: Build the project
      run: npm run build --if-present
      env:
        API_KEY: ${{ secrets.RIOT_API_KEY }}
      working-directory: ./my-app
    - name: Run tests
      run: npm test
      working-directory: ./my-app